/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocalRouteImport } from './routes/local'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesIndexRouteImport } from './routes/pages/index'
import { Route as SessionsSessionKeyRouteImport } from './routes/sessions/$sessionKey'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as PagesPageIdRouteImport } from './routes/pages/$pageId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesRoute,
} as any)
const SessionsSessionKeyRoute = SessionsSessionKeyRouteImport.update({
  id: '/sessions/$sessionKey',
  path: '/sessions/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPageIdRoute = PagesPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => PagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/local': typeof LocalRoute
  '/login': typeof LoginRoute
  '/pages': typeof PagesRouteWithChildren
  '/signup': typeof SignupRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/sessions/$sessionKey': typeof SessionsSessionKeyRoute
  '/pages/': typeof PagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/local': typeof LocalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/sessions/$sessionKey': typeof SessionsSessionKeyRoute
  '/pages': typeof PagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/local': typeof LocalRoute
  '/login': typeof LoginRoute
  '/pages': typeof PagesRouteWithChildren
  '/signup': typeof SignupRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/sessions/$sessionKey': typeof SessionsSessionKeyRoute
  '/pages/': typeof PagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/local'
    | '/login'
    | '/pages'
    | '/signup'
    | '/pages/$pageId'
    | '/room/$roomId'
    | '/sessions/$sessionKey'
    | '/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/local'
    | '/login'
    | '/signup'
    | '/pages/$pageId'
    | '/room/$roomId'
    | '/sessions/$sessionKey'
    | '/pages'
  id:
    | '__root__'
    | '/'
    | '/local'
    | '/login'
    | '/pages'
    | '/signup'
    | '/pages/$pageId'
    | '/room/$roomId'
    | '/sessions/$sessionKey'
    | '/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocalRoute: typeof LocalRoute
  LoginRoute: typeof LoginRoute
  PagesRoute: typeof PagesRouteWithChildren
  SignupRoute: typeof SignupRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  SessionsSessionKeyRoute: typeof SessionsSessionKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/sessions/$sessionKey': {
      id: '/sessions/$sessionKey'
      path: '/sessions/$sessionKey'
      fullPath: '/sessions/$sessionKey'
      preLoaderRoute: typeof SessionsSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$pageId': {
      id: '/pages/$pageId'
      path: '/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof PagesPageIdRouteImport
      parentRoute: typeof PagesRoute
    }
  }
}

interface PagesRouteChildren {
  PagesPageIdRoute: typeof PagesPageIdRoute
  PagesIndexRoute: typeof PagesIndexRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesPageIdRoute: PagesPageIdRoute,
  PagesIndexRoute: PagesIndexRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocalRoute: LocalRoute,
  LoginRoute: LoginRoute,
  PagesRoute: PagesRouteWithChildren,
  SignupRoute: SignupRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  SessionsSessionKeyRoute: SessionsSessionKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
